### ISSUE TITLE
Inactive m-lines shouldn't have mid attribute

### ISSUE THREAD

**Issue by benbro** [fippo/adapter#11]
expects mid on incoming inactive m-lines
https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js#L377

generates mid for all tracks, even when inactive
https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js#L648

**Comment by fippo** [comment]
while that should be fixed it looks like I need to change it again 'cause specs:
[webrtc-pc] Merged Pull Request: update MID to be random values when not  received in offer
