### ISSUE TITLE
add test for getSenders / getReceivers

### ISSUE THREAD

**Issue by fippo** [fippo/adapter#31]
need to find out what the expected behaviour is. On https://webrtc.github.io/samples/src/content/peerconnection/pc1/ firefox returns an empty array for pc2.getReceivers()

**Comment by jan-ivar** [comment]
@fippo try it again. :) Receivers were [added in Firefox 46](https://bugzilla.mozilla.org/show_bug.cgi?id=1232082), which shipped yesterday.

**Comment by fippo** [comment]
hah. so a test we might have to deactivate in ESR. Will check, many thanks!

**Comment by fippo** [comment]
so just the behaviour I expected. No receivers at the pc1 side (sendonly), no senders at pc2 (recvonly). Fab.
