### ISSUE TITLE
if addStream does not happen before setRemoteDescription the rtpSender sender is not created

### ISSUE THREAD

**Issue by fippo** [fippo/adapter#45]
https://github.com/webrtc/adapter/issues/514

The problem is in https://github.com/webrtc/adapter/blob/da86c9b3783ed22f16018a067ee44ff78320aea4/src/js/edge/rtcpeerconnection_shim.js#L721-L740

The RTPSender is only created if a local stream exists when setRemoteDescription is called.

Test:
```
    it.only('works when track is added after SRD', (done) => {
      const sdp = 'v=0\r\no=- 166855176514521964 2 IN IP4 127.0.0.1\r\n' +
          's=-\r\nt=0 0\r\na=msid-semantic: WMS\r\n' +
          'm=audio 9 UDP/TLS/RTP/SAVPF 98\r\n' +
          'c=IN IP4 0.0.0.0\r\n' +
          'a=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:foo\r\na=ice-pwd:bar\r\n' +
          'a=fingerprint:sha-256 so:me:co:lo:ns\r\n' +
          'a=setup:actpass\r\n' +
          'a=mid:audio1\r\n' +
          'a=sendrecv\r\na=rtcp-mux\r\n' +
          'a=rtcp-rsize\r\n' +
          'a=rtpmap:98 opus/48000\r\n' +
          'a=ssrc:1001 msid:stream1 track1\r\n' +
          'a=ssrc:1001 cname:some\r\n';
      pc.setRemoteDescription({type: 'offer', sdp: sdp})
      .then(() => {
        const audioTrack = new MediaStreamTrack();
        audioTrack.kind = 'audio';
        const stream = new MediaStream([audioTrack]);
        pc.addStream(stream);
        return pc.createAnswer();
      })
      .then((answer) => {
        const sections = SDPUtils.splitSections(answer.sdp);
        expect(SDPUtils.getDirection(sections[1])).to.equal('sendrecv');
        done();
      });
    });
```

**Comment by fippo** [comment]
The comment a bit down shows that the overall behaviour is slightly wrong:
```
        // Start the RTCRtpReceiver now. The RTPSender is started in
        // setLocalDescription.
```
the rtpsender should be created later as well. Well... maybe, depending on what the spec says.

**Comment by fippo** [comment]
@letchoo can you give 
https://github.com/fippo/adapter/commit/fb6a3dc93b76fe10c89e390eb21b99d404b1891d a try?

**Comment by letchoo** [comment]
Hi @fippo it seems like there is another PR that is merged: https://github.com/webrtc/adapter/pull/517. Just tested it and sometimes it worked but at times it didn't receive any video stream, which seems like the DTLS handshake failed:

> ORTC18615: ORTC RTCDtlsTransport: DTLS handshake failed. hr=c004e00f.

It seems like issue could comes from the ORTC API itself.
