### ISSUE TITLE
candidates after end-of-candidates / duplicate end of candidates

### ISSUE THREAD

**Issue by fippo** [fippo/adapter#6]
while dropping this into apprtc we noticed that this generates more than one end-of-candidates

**Comment by fippo** [comment]
one of the reasons was the apprtc sets offerToReceiveVideo to true so two gatherers are created. But that should not lead to invalidaccess errors.

**Comment by fippo** [comment]
hrm. I don't see those anymore. @KaptenJansson?

**Comment by KaptenJansson** [comment]
Sorry for missing this, do you want me to look into it still?

**Comment by fippo** [comment]
no... i'm working on automated interop tests :-)
